name: Daily Hashnode Bot

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      HASHNODE_API_KEY:   ${{ secrets.HASHNODE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python hashnode_bot.py
